<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>703029ee-ea8d-411c-bfa1-0c91fee0ec45</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.5.3-preview.1.26425.3" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
      <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.3" />
      <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OAuthMicroservice1\OAuthMicroservice1.csproj" />
      <ProjectReference Include="..\OAuthWeb\OAuthWeb.csproj" />
    </ItemGroup>

</Project>
